// src/lib/constants.ts
import type { Category } from './types';

export const CATEGORY_LABELS: Record<Category, string> = {
    accomodation: 'Accomodation',
    food:         'Food & Drink',
    transport:    'Transport',
    activities:   'Activities',
    shopping:     'Shopping',
    health:       'Health',
    other:        'Other',
};

export const CATEGORY_COLORS: Record<Category, string> = {
    accomodation: '#3B82F6',
    food:         '#F59E0B',
    transport:    '#8B5CF6',
    activities:   '#10B981',
    shopping:     '#EC4899',
    health:       '#EF4444',
    other:        '#6B7280',
};

export const CATEGORY_ICONS : Record<string, string> = {
  accomodation: '🏨',
  food: '🍜',
  transport: '🚌',
  activities: '🎭',
  shopping: '🛍️',
  health: '💊',
  other: '📦',
};

export const COUNTRY_CURRENCIES: Record<string, string> = {
  // Southeast Asia
  Thailand:      'THB',
  Vietnam:       'VND',
  Indonesia:     'IDR',
  Cambodia:      'USD',
  Laos:          'LAK',
  Myanmar:       'MMK',
  Philippines:   'PHP',
  Malaysia:      'MYR',
  Singapore:     'SGD',
  // South Asia
  India:         'INR',
  Nepal:         'NPR',
  'Sri Lanka':   'LKR',
  Maldives:      'MVR',
  // East Asia
  Japan:         'JPY',
  'South Korea': 'KRW',
  Taiwan:        'TWD',
  China:         'CNY',
  // Europe
  Portugal:      'EUR',
  Spain:         'EUR',
  Italy:         'EUR',
  Greece:        'EUR',
  Germany:       'EUR',
  France:        'EUR',
  Netherlands:   'EUR',
  Austria:       'EUR',
  Belgium:       'EUR',
  Ireland:       'EUR',
  'Czech Republic': 'CZK',
  Hungary:       'HUF',
  Poland:        'PLN',
  Croatia:       'EUR',
  Romania:       'RON',
  Bulgaria:      'BGN',
  Serbia:        'RSD',
  Albania:       'ALL',
  'North Macedonia': 'MKD',
  Montenegro:    'EUR',
  'Bosnia and Herzegovina': 'BAM',
  Switzerland:   'CHF',
  Norway:        'NOK',
  Sweden:        'SEK',
  Denmark:       'DKK',
  Finland:       'EUR',
  Iceland:       'ISK',
  'United Kingdom': 'GBP',
  Turkey:        'TRY',
  // Americas
  Mexico:        'MXN',
  Colombia:      'COP',
  Peru:          'PEN',
  Bolivia:       'BOB',
  Argentina:     'ARS',
  Brazil:        'BRL',
  Chile:         'CLP',
  Ecuador:       'USD',
  Paraguay:      'PYG',
  Uruguay:       'UYU',
  'Costa Rica':  'CRC',
  Guatemala:     'GTQ',
  Panama:        'USD',
  Cuba:          'CUP',
  'Dominican Republic': 'DOP',
  'United States': 'USD',
  Canada:        'CAD',
  // Africa
  Morocco:       'MAD',
  'South Africa':'ZAR',
  Egypt:         'EGP',
  Kenya:         'KES',
  Tanzania:      'TZS',
  Ethiopia:      'ETB',
  Ghana:         'GHS',
  Nigeria:       'NGN',
  Senegal:       'XOF',
  Tunisia:       'TND',
  Algeria:       'DZD',
  Mauritius:     'MUR',
  Botswana:      'BWP',
  Namibia:       'NAD',
  Rwanda:        'RWF',
  Uganda:        'UGX',
  Zambia:        'ZMW',
  Zimbabwe:      'USD',
  Somalia:       'SOS',
  'Sierra Leone': 'SLL',
  'Côte d\'Ivoire': 'XOF',
  Liberia:        'LRD',
  Cameroon:       'XAF',
  Madagascar:     'MGA',
  Mozambique:     'MZN',
  Angola:         'AOA',
  Gabon:          'XAF',
  'Central African Republic': 'XAF',
  'Democratic Republic of the Congo': 'CDF',
  'Republic of the Congo': 'XAF',
  // Oceania
  Australia:     'AUD',
  'New Zealand': 'NZD',
  Fiji:          'FJD',
  Vanuatu:       'VUV',
  Samoa:         'WST',
  'Papua New Guinea': 'PGK',
  'Solomon Islands': 'SBD',
  // Middle East
  Israel:        'ILS',
  Jordan:        'JOD',
  'United Arab Emirates': 'AED',
  Georgia:       'GEL',
  Armenia:       'AMD',
  Azerbaijan:    'AZN',
};

export const COUNTRY_FLAGS: Record<string, string> = {
  Thailand:      '🇹🇭', Vietnam:       '🇻🇳', Indonesia:     '🇮🇩', Maldives:      '🇲🇻', Ethiopia:       '🇪🇹',
  Cambodia:      '🇰🇭', Laos:          '🇱🇦', Myanmar:       '🇲🇲', Belgium:       '🇧🇪', Ghana:       '🇬🇭',
  Philippines:   '🇵🇭', Malaysia:      '🇲🇾', Singapore:     '🇸🇬', Ireland:       '🇮🇪', Nigeria:       '🇳🇬',
  India:         '🇮🇳', Nepal:         '🇳🇵', 'Sri Lanka':   '🇱🇰', Romania:       '🇷🇴', Senegal:       '🇸🇳',
  Japan:         '🇯🇵', 'South Korea': '🇰🇷', Taiwan:        '🇹🇼', Bulgaria:      '🇧🇬', Tunisia:       '🇹🇳',
  China:         '🇨🇳', Portugal:      '🇵🇹', Spain:         '🇪🇸', Serbia:       '🇷🇸', Algeria:       '🇩🇿',
  Italy:         '🇮🇹', Greece:        '🇬🇷', Germany:       '🇩🇪', Albania:       '🇦🇱', Mauritius:    '🇲🇺',
  France:        '🇫🇷', Netherlands:   '🇳🇱', Austria:       '🇦🇹', 'North Macedonia': '🇲🇰', Botswana:       '🇧🇼',
  'Czech Republic': '🇨🇿', Hungary:    '🇭🇺', Poland:        '🇵🇱', Montenegro:    '🇲🇪', Namibia:       '🇳🇦',
  Croatia:       '🇭🇷', Switzerland:   '🇨🇭', Norway:        '🇳🇴', 'Bosnia and Herzegovina': '🇧🇦', Rwanda: '🇷🇼',
  Sweden:        '🇸🇪', Denmark:       '🇩🇰', 'United Kingdom': '🇬🇧', Finland:       '🇫🇮', Uganda:      '🇺🇬',
  Turkey:        '🇹🇷', Mexico:        '🇲🇽', Colombia:      '🇨🇴', Iceland:       '🇮🇸', Zambia:         '🇿🇲',
  Peru:          '🇵🇪', Bolivia:       '🇧🇴', Argentina:     '🇦🇷', Ecuador:       '🇪🇨', Zimbabwe:       '🇿🇼',
  Brazil:        '🇧🇷', Chile:         '🇨🇱', 'Costa Rica':  '🇨🇷', Paraguay:      '🇵🇾', Somalia:        '🇸🇴',
  'United States': '🇺🇸', Canada:      '🇨🇦', Morocco:       '🇲🇦', Uruguay:       '🇺🇾', 'Sierra Leone': '🇸🇱',
  'South Africa':'🇿🇦', Egypt:         '🇪🇬', Kenya:         '🇰🇪', Guatemala:     '🇬🇹', 'Côte d\'Ivoire': '🇨🇮',
  Tanzania:      '🇹🇿', Australia:     '🇦🇺', 'New Zealand': '🇳🇿', Panama:        '🇵🇦', Liberia:        '🇱🇷',
  Israel:        '🇮🇱', Jordan:        '🇯🇴', 'United Arab Emirates': '🇦🇪', Cuba:  '🇨🇺', Cameroon:       '🇨🇲',
  Georgia:       '🇬🇪', Armenia:       '🇦🇲', Angola:        '🇦🇴', 'Dominican Republic': '🇩🇴', Madagascar: '🇲🇬',
  Azerbaijan:    '🇦🇿', Gabon:         '🇬🇦', 'Central African Republic': '🇨🇫', 'Democratic Republic of the Congo': '🇨🇩', 'Republic of the Congo': '🇨🇬',
  Fiji:          '🇫🇯', Vanuatu:       '🇻🇺', Samoa:         '🇼🇸', 'Papua New Guinea': '🇵🇬', 'Solomon Islands': '🇸🇧', Mozambique: '🇲🇿',
};

// Crowdsourced average daily budgets in USD (for backpackers)
export const COUNTRY_BUDGETS: Record<string, number> = {
    'Thailand':    35,
    'Vietnam':     30,
    'Indonesia':   35,
    'Cambodia':    30,
    'Laos':        25,
    'Myanmar':     30,
    'Philippines': 35,
    'Malaysia':    45,
    'India':       25,
    'Nepal':       25,
    'Portugal':    65,
    'Spain':       70,
    'Italy':       80,
    'Greece':      60,
    'Germany':     75,
    'Czech Republic':  55,
    'Hungary':     50,
    'Poland':      50,
    'Croatia':     65,
    'Mexico':      45,
    'Colombia':    40,
    'Peru':        40,
    'Bolivia':     30,
    'Argentina':   45,
    'Brazil':      50,
    'Morocco':     40,
    'South Africa':50,
    'Japan':       80,
    'South Korea': 60,
    'Taiwan':      50,
};

export const HOME_CURRENCIES = [
  'USD','EUR','GBP','AUD','CAD','CHF','JPY','SGD','NZD',
  'SEK','NOK','DKK','PLN','CZK','HUF','MXN','BRL','INR','ZAR',
];